# Generated by Django 2.2.5 on 2019-09-26 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0002_auto_20190925_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='cloak_timer',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='cloaked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='combat_timer',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='health',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='room',
            name='safe',
            field=models.BooleanField(default=False),
        ),
    ]
